### ISSUE TITLE
Just a theoretical question

### ISSUE THREAD

**Issue by konmik** [mattlogan/Pancakes#5]
Hi, why do you need `ViewFactory`? I hardly can imagine any need in it except for that cases when you want to build a view tree at runtime (which is a so rare case you could easily drop for the library simplicity).  In 99% cases I would say that passing a layout id instead of a factory is enough. What are your considerations here?

**Comment by frostymarvelous** [comment]
I suspect it's because it meant to replace fragments.

In this situation, you are right. It can easily be dropped and a simpler method introduced.
In my fork however, since I will be adding lifecycle events, this makes sense as the intent is to replace fragments.

**Comment by mattlogan** [comment]
Hey @konmik, sorry for the late reply here. I haven't really been focusing on this library too much and your question was too much of a head-scratcher for me to reply immediately.

I think the reason I went with ViewFactory instead of int/Integer layout ids was to allow the user to build Views however they like. I know some people prefer to use the <merge> tag as the root and inflate their view from XML in their custom View constructor. Some others might not even want to use XML at all. 

That said, I like the idea of making things simpler. And in my sample app (and probably most use cases), this would work fine.

Maybe I'll switch to using layout ids for a 4.0 release. Thanks for the suggestion.
